### ISSUE TITLE
Error: Invalid LngLat object: (NaN, NaN)

### ISSUE THREAD

**Issue by nicke** [cedbossneo/openmower-gui#19]
Today I updated openmower-gui. Now can't see the map. In JS console I see after "PATH Stream connected" this error:

index-4c85440c.js:628 Error: Invalid LngLat object: (NaN, NaN)
    at new po (mapbox-gl-fb74844c.js:8:78577)
    at po.convert (mapbox-gl-fb74844c.js:8:79468)
    at uo.setSouthWest (mapbox-gl-fb74844c.js:8:61980)
    at new uo (mapbox-gl-fb74844c.js:8:61783)
    at uo.convert (mapbox-gl-fb74844c.js:8:63382)
    at Map.cameraForBounds (mapbox-gl-fb74844c.js:1311:151652)
    at Map.fitBounds (mapbox-gl-fb74844c.js:1311:156012)
    at new Map (mapbox-gl-fb74844c.js:1316:13498)
    at nu._initialize (index-4c85440c.js:628:98602)
    at new nu (index-4c85440c.js:628:97237)

**Comment by wjcloudy** [comment]
Same issue here!

**Comment by wjcloudy** [comment]
If I revert to pr-9 image it works fine

**Comment by cedbossneo** [comment]
Should be fixed now

**Comment by wjcloudy** [comment]
Unfortunately new (but similar) error now: 
Unexpected Application Error!
coordinates must contain numbers

Error: coordinates must contain numbers
    at ple (http://192.168.1.118:4006/assets/index-539a7822.js:628:13157)
    at hle (http://192.168.1.118:4006/assets/index-539a7822.js:628:14565)
    at http://192.168.1.118:4006/assets/index-539a7822.js:628:148580
    at Array.flatMap (<anonymous>)
    at le (http://192.168.1.118:4006/assets/index-539a7822.js:628:148491)
    at http://192.168.1.118:4006/assets/index-539a7822.js:628:148789
    at Tv (http://192.168.1.118:4006/assets/index-539a7822.js:40:24283)
    at _c (http://192.168.1.118:4006/assets/index-539a7822.js:40:42406)
    at QE (http://192.168.1.118:4006/assets/index-539a7822.js:40:36624)
    at yl (http://192.168.1.118:4006/assets/index-539a7822.js:38:3279)
